### ISSUE TITLE
Source problem

### ISSUE THREAD

**Issue by Wall0fDeath** [OctopyID/LaraInotify#1]
Hi! 
I've tried to use this ext, but no matter what kind of source i gave to it, it always said, there is nothing to watch.

It seems in Inotify.php construct function it tries to check the inner "source" var. If it's not null ( what will never happen at start ), it will try to add that source:

==================================
```
public function __construct(string|null $source = null, Closure|null $event = null)
{
  //if (! is_null($this->source)) { //original, this will always be empty at the start
  if (! is_null($source)) {            // it started to work after i changed it to this
    $this->source(new InotifySource($source));
  }
  ...
}
```
===================================

Am I doing something wrong or is it a bug?

My code:

```
$inotify = new Inotify( "/tmp/test_dir/", function (Event $event) {
   $event->on(IN_CREATE, function (Watcher $watcher) {
      Log::info("It was creation");
    });
});
$inotify->watch();
```

Can I get the filename somehow out of the $watcher object?

**Comment by SupianIDz** [comment]
@Wall0fDeath You're right, I forgot the property. I'll fix it.
